### Root route
GET http://localhost:3000/

### Health check, demonstrates @Headers()
GET http://localhost:3000/health
User-Agent: nestjs-learning-http-file

### Get all users
GET http://localhost:3000/users

### Search users with @Query()
GET http://localhost:3000/users?keyword=ali

### Get one user with @Param()
GET http://localhost:3000/users/1

### Create user with @Body()
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Charlie",
  "age": 25
}

### Update user with @Param() and @Body()
PATCH http://localhost:3000/users/3
Content-Type: application/json

{
  "age": 26
}

### Delete user with @Param()
DELETE http://localhost:3000/users/3
